# 网站标题
title: 撒也不懂
# 网站标题后缀
suffix: 
# 作者名称
author: EurekaHaha
# 网站关键字
keyword: web前端,基础
#false是否开启文章背景图显示(随机图片)
is_article_img: true
# 网站描述
web_description: 瞎写
# 首页文章布局 默认 'card' 可选择 'block-card'
home_layout: block-card
# 导航名称
menus_title:
  home: HOME
  archive: ARCHIVE
  categories: CATEGORIES
  tags: TAGS
  links: LINKS
  about: ABOUT
# 导航 （不建议修改）
menus:
  home: /
  archive: /archives
  categories: /categories
  # tags: /tags
  # links: /links
  about: /about
  
# logo
logo: /image/L.JPG
# 网页标签上那个小图标 一定要用本地存储
icon: /image/favicon.ico
# 每个页面的展示的图标和一句话
headers:
    home: {
      message: "我只是引了一个好看点的主题",
      icon: "/image/L.JPG"
    }
    archives: {
      # 这里会替换掉两个变量{ year 年，number 总数 } 当然也可以不写这两个变量
      message: "居然用了 year 年一共才写了 number 篇文章!",
      icon: "/image/L.JPG"
    }
    # tags: {
    #   message: "这里是一些展示的标签",
    #   icon: "/image/L.JPG"
    # }
    # links: {
    #   message: "我和我的小伙伴们",
    #   icon: "/image/sad.jpg"
    # }
    categories: {
      message: "文章分类",
      icon: "/image/sad.jpg"
    }

# 网页访问统计
web_analytics:  
  enable: false #需要改为true
  baidu: 4b5fe1472f22fadsfs  # （替换）百度统计的 Key，参见 https://tongji.baidu.com/sc-web/10000033910/home/site/getjs?siteId=13751376 代码获取中 hm.js? 后边的字符串
# 评论 
gitalk:
  clientID: 53ec83ad9e565ded2dc5 # （需要替换）GitHub Application Client ID.
  clientSecret: 38051ecdf42a0c858a3bf82f730aec5a634344b3 #（需要替换）GitHub Application Client Secret.
  repo: EurekaHaha.github.io #（需要替换）GitHub repository.
  owner: EurekaHaha #（需要替换）GitHub repository 所有者，可以是个人或者组织。
  admin: ['EurekaHaha'] #（需要替换）GitHub repository 的所有者和合作者 (对这个 repository 有写权限的用户)。

# 底部显示的图标（github 或者其他）
bottomIcon: 
  #可以多个
  - {
    #描述名称
    name: 'Github',
    #图标    
    iconLink: 'https://avatars.githubusercontent.com/u/22878755?s=40&v=4',
    #跳转链接    
    toUrl: 'https://github.com/'
  }
# 友情链接
linksList:
  - {
    title: 'google',
    intro: '有问题 找谷歌',
    link: 'https://www.google.com',
    image: '/image/sad.jpg'
  }

#默认的cover (默认缩略图) 在没有填写（这里可以替换（可以是api也可以是固定的图））
default_cover: http://eett.cc/pictures?type=pc&category=fengjing